### ISSUE TITLE
Migrate IO class from TopoStats

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/AFMReader#22]
We should migrate the functionality in the [`topostats.io.LoadScan` class](https://github.com/AFM-SPM/TopoStats/blob/5a6a7609cde4c40804f37226991a612e0f38fae4/topostats/io.py#L447) from TopoStats to ~`topofileformats`~ `AFMReader`.

This will supersede issues #1 , #16 and #17 which are all file formats that are currently supported by `TopoStats`.

The migration should be done in two stages...

+ [x] Firstly copy the class and methods over to ~`topofileformats`~ `AFMReader along with tests and ensure that the functionality works as a stand alone aspect of this package.
  + [x] `.asd` (in-progress see comment below)
  + [x] `.ibw`
  + [x] `.gwy` (in-progress, PR due soon 2024-05-07).
  + [x] `.jpk`
  + [x] `.spm
  + [x] `.topostats`
+ [x] Remove the use of `topostats.io.LoadScan` from TopoStats and instead import the class from ~`topofileformats.io.LoadScan`~ `AFMReader.io.LoadScan`.

Another thing to consider is to integrate the current `.asd` support into the migrated class and make it a method
available in the `LoadScan` class.

**Comment by SylviaWhittle** [comment]
Update: .jpk, .ibw, .spm have been added. .gwy needs adding and .asd needs a fix I'm adding soon.

**Comment by SylviaWhittle** [comment]
Update: Added `.topostats` format as of #53

**Comment by SylviaWhittle** [comment]
Update: Gwy migrated as of #61
